
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - brew install libmemcached
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - /usr/local/bin/memcached &
  - set -o pipefail && xcodebuild test -workspace OSX\ Projects/Memcached/Memcached.xcworkspace -scheme Memcached -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty
