language: objective-c
osx_image: xcode7.2
before_script:
  - brew install xctool
  - brew install libmemcached
  - /usr/local/bin/memcached &
  - ls OSX\ Projects/Memcached/
  - cd OSX\ Projects/Memcached/ && pod install
xcode_workspace: OSX Projects/Memcached/Memcached.xcworkspace
xcode_scheme: Memcached
xcode_sdk: macosx
