language: objective-c
osx_image: xcode7.2
before_script:
  - brew install xctool
  - brew install libmemcached
  - /usr/local/bin/memcached &
  - cd OSX\ Projects/Memcached/ && pod install
xcode_project: OSX\ Projects/Memcached/Memcached.xcworkspace
xcode_scheme: MemcachedTests
xcode_sdk: macosx
