source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :osx, '10.10'

target 'Memcached' do
    pod 'libmemcached', :path => "../../"
end

target 'MemcachedTests' do
    pod 'libmemcached', :path => "../../"
    pod 'Quick'
    pod 'Nimble'
end
